backend:
  name: git-gateway
  branch: main

media_folder: "photos"
public_folder: "/photos"

collections:
  - name: "gallery"
    label: "Photo Gallery"
    files:
      - file: "content/gallery.json"
        name: "gallery"
        label: "Job Photos"
        fields:
          - label: "Photos"
            name: "photos"
            widget: "list"
            summary: "{{fields.caption}}"
            field:
              label: "Photo"
              name: "photo"
              widget: "image"
